version: "3.8"

services:
  eventstoredb:
    image: eventstore/eventstore:latest
    container_name: eventstoredb
    volumes:
      - ${PWD}/eventstore/logs:/var/lib/eventstore # intended to be run from "{project_root}/services" folder
      - ${PWD}/eventstore/logs:/var/log/eventstore # intended to be run from "{project_root}/services" folder
    networks:
      - net
    ports:
      - "1113:1113" # map internal tcp port
      - "2113:2113" # map internal admin ui port
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true

networks:
  net:
    external: true
