version: '3.8'

services:
  domain-api:
    image: domain-api:1.0.0
    container_name: domain-api
    networks:
      - net
    ports:
      - "4001:4001"
    environment:
      PRODUCTION: false
      LOG_TO_HOST: logstash
      LOG_TO_PORT: 5000
      APIREST_API_PORT: 4001
      APIREST_EVENTSTOREDB_HOST: eventstoredb
      APIREST_EVENTSTOREDB_PORT: 2113

networks:
  net:
    external: true
